"use client"

import { motion } from "framer-motion"
import { ArrowUpRight, Github } from "lucide-react"

const projects = [
  { no: "01", category: "Distributed systems", title: "Cake Delight", sub: "Microservices-based cake ordering platform", description: "A distributed ordering platform built with independently organized services, API gateway routing, and asynchronous event-driven notifications.", tags: ["Java", "Spring Boot", "RabbitMQ", "Kubernetes"], diagram: "services", github: "https://github.com/prathibha-15" },
  { no: "02", category: "AI engineering · SAP Labs", title: "GenAI Vendor Ranking", sub: "Semantic discovery for complex datasets", description: "A GenAI-powered vendor discovery and ranking system using custom embeddings and vector search to retrieve relevant vendors from large datasets.", tags: ["FastAPI", "FAISS", "React", "Embeddings"], metric: "60%", metricLabel: "reported reduction in vendor discovery time", github: "https://github.com/prathibha-15/vendor-comparison-chatbot" },
  { no: "03", category: "Applied machine learning", title: "Yoga Pose Feedback", sub: "Real-time computer vision system", description: "A real-time pose classification and feedback system using MediaPipe and an SVM classifier to make movement analysis more accessible.", tags: ["Python", "MediaPipe", "SVM", "Computer vision"], metric: "90%", metricLabel: "reported classification accuracy", github: "https://github.com/prathibha-15/yoga-pose-estimation" },
]

function ServiceDiagram() { return <div className="diagram"><div className="diagram-node gateway">API Gateway</div><div className="diagram-row"><span>Catalog</span><span>Order</span><span>Rating</span></div><div className="diagram-line" /><div className="diagram-node queue">RabbitMQ <small>async events</small></div><div className="diagram-node notification">Notification service</div></div> }

export default function Projects() { return <section id="projects" className="section-shell"><div className="section-heading"><p className="eyebrow">Selected work</p><h2 className="section-title">Systems with a point<br /><em>of view.</em></h2><p className="section-intro">A selection of engineering work across distributed systems, applied AI, and computer vision.</p></div><div className="flex flex-col gap-5">{projects.map((project, index) => <motion.article key={project.no} initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-80px" }} transition={{ delay: index * 0.08 }} className="project-row"><div className="project-number">{project.no}</div><div className="project-copy"><p className="eyebrow mb-5">{project.category}</p><h3>{project.title}</h3><p className="project-sub">{project.sub}</p><p className="mt-6 max-w-lg leading-7 text-muted-foreground">{project.description}</p><div className="mt-7 flex flex-wrap gap-2">{project.tags.map(tag => <span className="tag" key={tag}>{tag}</span>)}</div><a className="project-link" href={project.github} target="_blank" rel="noreferrer">View on GitHub <Github className="size-4" /></a></div><div className="project-visual">{project.diagram === "services" ? <ServiceDiagram /> : <><div className="metric">{project.metric}</div><p>{project.metricLabel}</p><div className={`signal signal-${index}`} aria-hidden="true"><i /><i /><i /><i /><i /></div></>}</div></motion.article>)}</div></section> }
